"""Mini answer report generator — Phase 8: full Semantic RAG Mini Answer Report.

Generates a downloadable Markdown report from RAG Q&A output, retrieved evidence,
and optional retrieval comparison results.
All processing is local — no external AI API calls.
"""

import re
from datetime import date


_SAFE_CHARS = re.compile(r"[^a-z0-9]+")

_DEFAULT_LIMITATIONS = [
    (
        "This report is generated by a prototype using synthetic policy documents, "
        "local embeddings, FAISS vector search, and deterministic answer/report logic. "
        "It is intended to support discussion, evidence review, and learning about RAG workflows."
    ),
    (
        "This report is not legal, safeguarding, HR, compliance, medical, financial, "
        "academic-integrity, or professional advice."
    ),
    (
        "Retrieved chunks may not include all relevant policy context. "
        "Similarity scores are ranking signals, not confidence scores. "
        "Users should review the full source documents before acting."
    ),
    (
        "Do not use this prototype with real learner data, safeguarding case details, "
        "confidential client records, staff HR data, personal data, or regulated information "
        "unless appropriate governance, approvals, security controls, and responsible owners "
        "are in place."
    ),
]

_DEFAULT_REVIEWER_NOTES = [
    "Check whether the retrieved chunks directly support the answer.",
    "Review surrounding source-document sections.",
    "Confirm whether the answer misses important policy context.",
    "Check whether human review, escalation, or governance controls are needed.",
    "Treat this as evidence support, not final authority.",
]

_PROTOTYPE_STATUS = (
    "This is a production-style RAG prototype, not a production system. "
    "It currently demonstrates local document loading, chunking, local embeddings, "
    "FAISS vector indexing, semantic search, deterministic RAG Q&A, retrieval comparison, "
    "and Markdown reporting over synthetic documents."
)


def create_report_filename(title: str) -> str:
    """Return a safe lowercase filename for a report.

    Empty or whitespace-only titles default to 'semantic-rag-answer-report.md'.
    """
    if not title or not title.strip():
        return "semantic-rag-answer-report.md"
    slug = _SAFE_CHARS.sub("-", title.strip().lower()).strip("-")
    slug = slug or "semantic-rag-answer-report"
    return f"{slug}.md"


def get_default_report_limitations() -> list:
    """Return the standard responsible-use limitation strings."""
    return list(_DEFAULT_LIMITATIONS)


def format_detected_topics(topics: list) -> str:
    """Return a comma-separated string of detected topics, or a fallback message."""
    if not topics:
        return "No specific topics detected."
    return ", ".join(str(t) for t in topics)


def format_evidence_items(evidence_items: list, max_items: int = 8) -> str:
    """Return a Markdown-formatted block of evidence items.

    Returns a placeholder message if evidence_items is empty.
    """
    if not evidence_items:
        return "No evidence items available. Run the RAG Q&A page to retrieve evidence."
    lines = []
    for item in evidence_items[:max_items]:
        rank = item.get("rank", item.get("chunk_index", ""))
        score = item.get("score", "")
        doc = item.get("document_name", item.get("source_label", "Unknown"))
        chunk_id = item.get("chunk_id", "")
        chunk_index = item.get("chunk_index", "")
        text = item.get("evidence_text", item.get("text", ""))[:300]
        lines += [
            f"### Evidence item {rank}",
            f"- **Document:** {doc}",
            f"- **Chunk ID:** `{chunk_id}`",
            f"- **Chunk index:** {chunk_index}",
            f"- **Score:** {score}",
            "",
            f"> {text}",
            "",
        ]
    return "\n".join(lines)


def format_limitations(limitations: list) -> str:
    """Return a Markdown bullet list of limitation strings.

    Uses default limitations if the supplied list is empty.
    """
    if not limitations:
        return "\n".join(f"- {lim}" for lim in _DEFAULT_LIMITATIONS)
    return "\n".join(f"- {lim}" for lim in limitations)


def format_retrieval_comparison_section(comparison_result) -> str:
    """Return a Markdown summary of a retrieval comparison, or a placeholder if missing."""
    if not comparison_result:
        return (
            "No retrieval comparison is available yet. "
            "Run the Retrieval Comparison page to include this section."
        )
    ks = comparison_result.get("keyword_summary", {})
    ss = comparison_result.get("semantic_summary", {})
    overlap = comparison_result.get("overlap", [])
    insight = comparison_result.get("comparison_insight", "")

    lines = [
        f"- **Keyword results:** {ks.get('result_count', 0)} chunks from "
        f"{ks.get('unique_documents', 0)} document(s)",
        f"- **Semantic results:** {ss.get('result_count', 0)} chunks from "
        f"{ss.get('unique_documents', 0)} document(s)",
        f"- **Overlapping chunks:** {len(overlap)}",
        "",
        f"**Insight:** {insight}",
        "",
        "_Keyword search finds exact or near-exact term matches. "
        "Semantic search finds meaning-based matches using vector similarity. "
        "Overlap indicates strong evidence candidates agreed on by both methods._",
    ]
    return "\n".join(lines)


def build_report_data_from_session_state(session_state: dict) -> dict:
    """Build a report_data dict from Streamlit session_state (or any dict).

    All values have safe defaults — missing session keys will not raise errors.
    """
    rag_response = session_state.get("last_rag_response") or {}

    return {
        "report_title": session_state.get("report_title") or "Semantic RAG Policy Answer Report",
        "generated_date": str(date.today()),
        "question": (
            session_state.get("last_rag_question")
            or rag_response.get("question", "")
        ),
        "answer": (
            session_state.get("last_rag_answer")
            or rag_response.get("answer", "")
        ),
        "detected_topics": rag_response.get("detected_topics", []),
        "question_type": rag_response.get("question_type", "unknown"),
        "needs_caution": rag_response.get("needs_caution", False),
        "caution_reason": rag_response.get("caution_reason", ""),
        "model_name": (
            session_state.get("embedding_model_name")
            or rag_response.get("model_name", "sentence-transformers/all-MiniLM-L6-v2")
        ),
        "retrieval_metric": (
            session_state.get("vector_metric")
            or rag_response.get("metric", "cosine")
        ),
        "top_k": rag_response.get("top_k", 5),
        "evidence_items": (
            session_state.get("last_rag_evidence")
            or rag_response.get("evidence_summary", [])
            or []
        ),
        "semantic_results": session_state.get("last_semantic_results") or [],
        "keyword_results": session_state.get("last_keyword_results") or [],
        "comparison_result": session_state.get("last_retrieval_comparison"),
        "limitations": rag_response.get("limitations") or get_default_report_limitations(),
        "reviewer_notes": session_state.get("reviewer_notes") or list(_DEFAULT_REVIEWER_NOTES),
    }


def generate_markdown_answer_report(report_data: dict) -> str:
    """Generate a full 10-section Semantic RAG Mini Answer Report.

    Recognised keys (all optional): report_title, question, answer, detected_topics,
    question_type, needs_caution, caution_reason, model_name, retrieval_metric, top_k,
    evidence_items, sources, comparison_result, limitations, reviewer_notes,
    generated_date, retrieval_method.

    Backward compatible: accepts old keys 'sources' and 'retrieval_method'.
    Returns a non-empty Markdown string.
    """
    report_title = report_data.get("report_title", "Semantic RAG Policy Answer Report")
    generated_date = report_data.get("generated_date", str(date.today()))
    question = report_data.get("question", "")
    answer = report_data.get("answer", "")
    detected_topics = report_data.get("detected_topics", [])
    question_type = report_data.get("question_type", "")
    needs_caution = report_data.get("needs_caution", False)
    caution_reason = report_data.get("caution_reason", "")
    model_name = report_data.get("model_name", "sentence-transformers/all-MiniLM-L6-v2")
    retrieval_metric = report_data.get(
        "retrieval_metric",
        report_data.get("retrieval_method", "cosine"),
    )
    top_k = report_data.get("top_k", 5)

    # Support both old key (sources) and new key (evidence_items)
    evidence_items = report_data.get("evidence_items") or []
    if not evidence_items:
        old_sources = report_data.get("sources", [])
        evidence_items = [
            {
                "rank": i + 1,
                "score": "",
                "document_name": s.get("document_name", ""),
                "chunk_id": s.get("chunk_id", ""),
                "chunk_index": "",
                "evidence_text": s.get("text", ""),
            }
            for i, s in enumerate(old_sources)
        ]

    comparison_result = report_data.get("comparison_result")
    limitations = report_data.get("limitations") or get_default_report_limitations()
    reviewer_notes = report_data.get("reviewer_notes") or list(_DEFAULT_REVIEWER_NOTES)

    lines = [
        "# Semantic RAG Mini Answer Report",
        "",
        f"**Report:** {report_title}",
        f"**Generated:** {generated_date}",
        "",
        "> **Responsible-use notice:** This report was generated from synthetic documents only. "
        "It does not constitute legal, safeguarding, HR, compliance, or professional advice. "
        "Human review is required before acting on any output.",
        "",
        "---",
        "",
    ]

    # 1. Question
    lines += ["## 1. Question", ""]
    if question:
        lines += [question, ""]
    else:
        lines += [
            "No RAG question has been generated yet. Run the RAG Q&A page first.",
            "",
        ]

    # 2. Short Grounded Answer
    lines += ["## 2. Short Grounded Answer", ""]
    if answer:
        lines += [answer, ""]
    else:
        lines += ["No answer available. Run the RAG Q&A page first.", ""]

    # 3. Detected Topics and Question Type
    lines += ["## 3. Detected Topics and Question Type", ""]
    lines += [f"- **Detected topics:** {format_detected_topics(detected_topics)}"]
    if question_type:
        lines += [f"- **Question type:** {question_type}"]
    if needs_caution:
        lines += ["- **Caution required:** Yes"]
        if caution_reason:
            lines += [f"- **Caution reason:** {caution_reason}"]
    else:
        lines += ["- **Caution required:** No"]
    lines += [""]

    # 4. Retrieval Setup
    lines += [
        "## 4. Retrieval Setup",
        "",
        f"- **Embedding model:** {model_name}",
        f"- **Retrieval metric:** {retrieval_metric}",
        f"- **Top-k:** {top_k}",
        "- **Index type:** FAISS (local)",
        "- **Note:** This version uses local embeddings and FAISS vector search. "
        "No external AI API calls are made.",
        "",
    ]

    # 5. Retrieved Evidence
    lines += ["## 5. Retrieved Evidence", ""]
    lines += [format_evidence_items(evidence_items), ""]

    # 6. Retrieval Comparison Summary
    lines += ["## 6. Retrieval Comparison Summary", ""]
    lines += [format_retrieval_comparison_section(comparison_result), ""]

    # 7. Caution Notes
    lines += ["## 7. Caution Notes", ""]
    if needs_caution and caution_reason:
        lines += [f"> {caution_reason}", ""]
    else:
        lines += [
            "No specific caution flag was detected, but human review remains required.",
            "",
        ]

    # 8. Limitations and Responsible Use
    lines += ["## 8. Limitations and Responsible Use", ""]
    lines += [format_limitations(limitations), ""]

    # 9. Reviewer Notes
    lines += ["## 9. Reviewer Notes", ""]
    for note in reviewer_notes:
        lines += [f"- {note}"]
    lines += [""]

    # 10. Prototype Status
    lines += ["## 10. Prototype Status", "", _PROTOTYPE_STATUS, ""]

    lines += [
        "---",
        "",
        "*Semantic RAG Policy Assistant · BrightPath ChatGPT Mastery Project*",
        "*All documents are synthetic. Outputs are indicative only.*",
    ]

    return "\n".join(lines)
