"""
Tests for src/qa_engine.py

Run from the project root:  pytest
"""

from src.qa_engine import (
    detect_topics_from_question,
    generate_policy_answer,
    get_question_limitations,
    answer_policy_question,
    generate_qa_markdown,
)

# ── Fixtures ──────────────────────────────────────────────────────────────────

MINIMAL_DOCS = {
    "test_policy.md": (
        "Staff must not enter learner data into AI tools.\n"
        "Safeguarding concerns must be escalated to the designated safeguarding lead.\n"
        "AI outputs must be reviewed by a responsible member of staff before use.\n"
        "Staff should use only organisation-approved AI tools for work.\n"
        "Any data breach or incident should be reported to the data protection lead.\n"
        "Staff should check for bias and inaccuracies in AI-generated outputs.\n"
        "Do not enter safeguarding case details into any AI tool.\n"
        "Apply data minimisation when working with AI tools.\n"
        "All AI outputs must have a named responsible owner.\n"
    )
}

SAMPLE_EVIDENCE = [
    {
        "topic": "learner data",
        "document_name": "test_policy.md",
        "line_number": 1,
        "evidence_text": "Staff must not enter learner data into AI tools.",
        "matched_keywords": ["learner data"],
        "relevance_count": 1,
    },
    {
        "topic": "safeguarding",
        "document_name": "test_policy.md",
        "line_number": 2,
        "evidence_text": "Safeguarding concerns must be escalated to the designated safeguarding lead.",
        "matched_keywords": ["safeguarding", "safeguarding lead"],
        "relevance_count": 2,
    },
]

SAMPLE_QA_RESULT = {
    "question": "Can staff enter learner data into AI tools?",
    "detected_topics": ["learner data", "approved tools", "data minimisation", "anonymisation", "human review"],
    "answer": "Based on the synthetic policy documents: staff should not enter learner data.",
    "evidence_results": SAMPLE_EVIDENCE,
    "safeguards": ["Do not enter identifiable learner data.", "Use synthetic examples."],
    "owners": ["Data protection lead / senior manager"],
    "limitations": ["This answer is generated by keyword matching."],
    "coverage_note": "Evidence found in one document only.",
    "risk_summary_items": [],
}


# ── detect_topics_from_question ───────────────────────────────────────────────

def test_detect_topics_returns_list():
    result = detect_topics_from_question("any question")
    assert isinstance(result, list)


def test_detect_topics_learner_data_question():
    result = detect_topics_from_question("Can staff enter learner data into AI tools?")
    assert "learner data" in result


def test_detect_topics_learner_data_adds_co_detected_topics():
    result = detect_topics_from_question("Can staff enter learner data into AI tools?")
    assert "data minimisation" in result
    assert "human review" in result


def test_detect_topics_safeguarding_question():
    result = detect_topics_from_question("What does the policy say about safeguarding information and AI?")
    assert "safeguarding" in result


def test_detect_topics_safeguarding_adds_escalation():
    result = detect_topics_from_question("What does the policy say about safeguarding information?")
    assert "escalation" in result


def test_detect_topics_human_review_question():
    result = detect_topics_from_question("What human review is required for AI-generated outputs?")
    assert "human review" in result


def test_detect_topics_human_review_adds_accountability():
    result = detect_topics_from_question("What human review is required?")
    assert "accountability" in result


def test_detect_topics_hallucination_from_inaccurate():
    result = detect_topics_from_question("What should staff do if AI output seems inaccurate or unsafe?")
    assert "hallucination" in result


def test_detect_topics_hallucination_adds_bias():
    result = detect_topics_from_question("What should staff do if AI output seems inaccurate?")
    assert "bias" in result


def test_detect_topics_accountability_from_responsible():
    result = detect_topics_from_question("Who is responsible for AI-assisted outputs?")
    assert "accountability" in result


def test_detect_topics_accountability_adds_human_review():
    result = detect_topics_from_question("Who is responsible for AI-assisted outputs?")
    assert "human review" in result


def test_detect_topics_incident_reporting_from_accidentally():
    result = detect_topics_from_question(
        "What should staff do if they accidentally enter sensitive information into an AI tool?"
    )
    assert "incident reporting" in result


def test_detect_topics_empty_question_returns_empty():
    assert detect_topics_from_question("") == []


def test_detect_topics_whitespace_only_returns_empty():
    assert detect_topics_from_question("   ") == []


def test_detect_topics_no_match_returns_empty_list():
    result = detect_topics_from_question("What is the capital of France?")
    assert isinstance(result, list)


def test_detect_topics_returns_list_of_strings():
    result = detect_topics_from_question("Can staff enter learner data into AI tools?")
    assert all(isinstance(t, str) for t in result)


def test_detect_topics_no_duplicates():
    result = detect_topics_from_question(
        "Can staff enter learner data into AI tools?"
    )
    assert len(result) == len(set(result))


# ── generate_policy_answer ────────────────────────────────────────────────────

def test_generate_policy_answer_returns_string():
    result = generate_policy_answer("", ["learner data"], SAMPLE_EVIDENCE, [])
    assert isinstance(result, str)


def test_generate_policy_answer_no_topics_returns_cautious():
    result = generate_policy_answer("any question", [], [], [])
    assert "topic" in result.lower() or "identify" in result.lower()


def test_generate_policy_answer_no_evidence_returns_no_evidence_message():
    result = generate_policy_answer("question", ["safeguarding"], [], [])
    assert "evidence" in result.lower() or "document" in result.lower()


def test_generate_policy_answer_no_evidence_does_not_say_policy_documents():
    result = generate_policy_answer("question", ["safeguarding"], [], [])
    assert "Based on the synthetic policy documents" not in result


def test_generate_policy_answer_with_evidence_contains_policy_prefix():
    result = generate_policy_answer("question", ["safeguarding"], SAMPLE_EVIDENCE, [])
    assert "Based on the synthetic policy documents" in result


def test_generate_policy_answer_safeguarding_produces_relevant_text():
    result = generate_policy_answer("", ["safeguarding"], SAMPLE_EVIDENCE, [])
    assert "safeguarding" in result.lower()


def test_generate_policy_answer_learner_data_produces_relevant_text():
    result = generate_policy_answer("", ["learner data"], SAMPLE_EVIDENCE, [])
    assert "learner" in result.lower()


def test_generate_policy_answer_multiple_topics_combines_text():
    single = generate_policy_answer("", ["learner data"], SAMPLE_EVIDENCE, [])
    multi = generate_policy_answer("", ["learner data", "safeguarding"], SAMPLE_EVIDENCE, [])
    assert len(multi) >= len(single)


# ── get_question_limitations ──────────────────────────────────────────────────

def test_get_question_limitations_returns_list():
    result = get_question_limitations(["safeguarding"], SAMPLE_EVIDENCE)
    assert isinstance(result, list)


def test_get_question_limitations_returns_non_empty():
    result = get_question_limitations(["safeguarding"], SAMPLE_EVIDENCE)
    assert len(result) >= 1


def test_get_question_limitations_items_are_strings():
    result = get_question_limitations(["learner data"], SAMPLE_EVIDENCE)
    assert all(isinstance(item, str) for item in result)


def test_get_question_limitations_contains_keyword_matching_note():
    result = get_question_limitations(["safeguarding"], SAMPLE_EVIDENCE)
    combined = " ".join(result).lower()
    assert "keyword" in combined or "matching" in combined


def test_get_question_limitations_no_evidence_adds_extra_note():
    with_evidence = get_question_limitations(["safeguarding"], SAMPLE_EVIDENCE)
    without_evidence = get_question_limitations(["safeguarding"], [])
    assert len(without_evidence) > len(with_evidence)


# ── answer_policy_question ────────────────────────────────────────────────────

def test_answer_policy_question_returns_dict():
    result = answer_policy_question("Can staff enter learner data?", MINIMAL_DOCS)
    assert isinstance(result, dict)


def test_answer_policy_question_has_question_key():
    result = answer_policy_question("Can staff enter learner data?", MINIMAL_DOCS)
    assert "question" in result


def test_answer_policy_question_has_detected_topics_key():
    result = answer_policy_question("Can staff enter learner data?", MINIMAL_DOCS)
    assert "detected_topics" in result


def test_answer_policy_question_has_answer_key():
    result = answer_policy_question("Can staff enter learner data?", MINIMAL_DOCS)
    assert "answer" in result


def test_answer_policy_question_has_evidence_results_key():
    result = answer_policy_question("Can staff enter learner data?", MINIMAL_DOCS)
    assert "evidence_results" in result


def test_answer_policy_question_has_safeguards_key():
    result = answer_policy_question("Can staff enter learner data?", MINIMAL_DOCS)
    assert "safeguards" in result


def test_answer_policy_question_has_owners_key():
    result = answer_policy_question("Can staff enter learner data?", MINIMAL_DOCS)
    assert "owners" in result


def test_answer_policy_question_has_limitations_key():
    result = answer_policy_question("Can staff enter learner data?", MINIMAL_DOCS)
    assert "limitations" in result


def test_answer_policy_question_has_coverage_note_key():
    result = answer_policy_question("Can staff enter learner data?", MINIMAL_DOCS)
    assert "coverage_note" in result


def test_answer_policy_question_preserves_question():
    q = "Can staff enter learner data into AI tools?"
    result = answer_policy_question(q, MINIMAL_DOCS)
    assert result["question"] == q


def test_answer_policy_question_single_doc_scope():
    result = answer_policy_question(
        "Can staff enter learner data?",
        MINIMAL_DOCS,
        selected_document="test_policy.md",
    )
    assert isinstance(result, dict)
    assert result["question"] == "Can staff enter learner data?"


def test_answer_policy_question_safeguards_is_list():
    result = answer_policy_question("Who is responsible for AI outputs?", MINIMAL_DOCS)
    assert isinstance(result["safeguards"], list)


def test_answer_policy_question_owners_is_list():
    result = answer_policy_question("Who is responsible for AI outputs?", MINIMAL_DOCS)
    assert isinstance(result["owners"], list)


# ── generate_qa_markdown ──────────────────────────────────────────────────────

def test_generate_qa_markdown_returns_string():
    assert isinstance(generate_qa_markdown(SAMPLE_QA_RESULT), str)


def test_generate_qa_markdown_contains_title():
    md = generate_qa_markdown(SAMPLE_QA_RESULT)
    assert "Evidence-Based Policy Q&A" in md


def test_generate_qa_markdown_contains_question_section():
    md = generate_qa_markdown(SAMPLE_QA_RESULT)
    assert "## Question" in md


def test_generate_qa_markdown_contains_short_answer_section():
    md = generate_qa_markdown(SAMPLE_QA_RESULT)
    assert "## Short Answer" in md


def test_generate_qa_markdown_contains_detected_topics_section():
    md = generate_qa_markdown(SAMPLE_QA_RESULT)
    assert "## Detected Topics" in md


def test_generate_qa_markdown_contains_evidence_found_section():
    md = generate_qa_markdown(SAMPLE_QA_RESULT)
    assert "## Evidence Found" in md


def test_generate_qa_markdown_contains_safeguards_section():
    md = generate_qa_markdown(SAMPLE_QA_RESULT)
    assert "## Recommended Safeguards" in md


def test_generate_qa_markdown_contains_owners_section():
    md = generate_qa_markdown(SAMPLE_QA_RESULT)
    assert "## Suggested Responsible Owners" in md


def test_generate_qa_markdown_contains_limitations_section():
    md = generate_qa_markdown(SAMPLE_QA_RESULT)
    assert "## Limitations" in md


def test_generate_qa_markdown_empty_result_still_returns_string():
    md = generate_qa_markdown({})
    assert isinstance(md, str)
    assert "## Question" in md
